#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install neovim
  brew install tmux
  brew install lua
  brew install luajit
  brew install jq
  brew install ripgrep
  brew install bear
  brew install luarocks
  brew install fzf
  brew install fnm
  brew install make
  brew install btop
  brew install zsh-autosuggestions
  brew install zsh-syntax-highlighting libpq
fi

